### PR TITLE
Updated Info Table & added "remove" method to CommandManager.java

### PR DESCRIPTION
**Pull request by Raymond-exe**
(*Without* the missing code this time)

### CODE REVIEW

**Comment by Kab1r** [comment]
next time mention the issue you are working on in the commit and pull request that fixes the issue #2

**Review by Kab1r — CHANGES_REQUESTED** [review]
commandPrefix is undefined in remove method

'D' in getID() should be lowercase, 'd' and getId()

temp variable seems redundant.
removedObj can be added to for loop arguments to reduce redundant looping

**Review by Kab1r — CHANGES_REQUESTED** [review]
sendMessage should be queued after being called

**Comment by Raymond-exe** [comment]
**Edits:** 
- Now calls `sendMessage(~).queue()`
- Loop now breaks if a match is found
- `temp` variable removed and instances were replaced with `prefixless`
- `getID()` replaced with `getId()`
- `commandPrefix` replaced with `database.getCommandPrefix(message.getGuild().getId())`

**Review by Kab1r — APPROVED** [review]

**Pull request merged**
